//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWebApplication.SaveWebPage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaveWebPage.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeWebPage", ReplyAction="http://tempuri.org/IService1/storeWebPageResponse")]
        string storeWebPage(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeWebPage", ReplyAction="http://tempuri.org/IService1/storeWebPageResponse")]
        System.Threading.Tasks.Task<string> storeWebPageAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NewsWebApplication.SaveWebPage.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NewsWebApplication.SaveWebPage.IService1>, NewsWebApplication.SaveWebPage.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string storeWebPage(string url) {
            return base.Channel.storeWebPage(url);
        }
        
        public System.Threading.Tasks.Task<string> storeWebPageAsync(string url) {
            return base.Channel.storeWebPageAsync(url);
        }
    }
}
